### ISSUE TITLE
Junk in strings (uninitialized?)

### ISSUE THREAD

**Issue by SanyaSho** [Joshua-Ashton/HL2-GamepadUI#11]
![изображение](https://user-images.githubusercontent.com/68691958/218392357-e20e0c6c-dd7e-4714-bc91-0bf5df55207d.png)
![изображение](https://user-images.githubusercontent.com/68691958/218392481-c338afc7-4c8c-4d36-9184-1808a7cb54c1.png)

**Comment by Nbc66** [comment]
https://github.com/Nbc66/source-sdk-2013-ce/commit/11d0a99a8dc879e7b3c38904d3161e987f9c1b5d

This commit fixes the utf 8 chars not being set to null. I will do a pull request soon to fix those or @DasMaddi can take a look at it and puah it to the repo

**Comment by DasMaddi** [comment]
Thanks Kerim I'll get this merged over shortly.
