### ISSUE TITLE
how can i get this to work with mapbase

### ISSUE THREAD

**Issue by breakdowngamesYT** [Joshua-Ashton/HL2-GamepadUI#15]
im making a mod in Mapbase and I would very much like to use this

**Comment by DasMaddi** [comment]
Unless the mapbase team merges GamepadUI into their own existing builds, you'll need to compile the project yourself for compatibility at the moment; Instructions are provided on the front page. The pre built binaries only work for stock SDK2013.

**Comment by breakdowngamesYT** [comment]
this what i did it has errors

**Comment by DasMaddi** [comment]
Try now. We updated the readme with a missing step to get it compiling. Apologies.

**Comment by breakdowngamesYT** [comment]
it still has errors 

i give you error 1:
error LNK2001: unresolved external symbol "bool g_bUsingCustomHudAnimations" (?g_bUsingCustomHudAnimations@@3_NA)	D:\mapbase-expanded-source-develop\sp\src\game\gamepadui\vgui_controls.lib(AnimationController.obj)	GamepadUI (EZ2)

and error 2
error LNK1120: 1 unresolved externals	D:\mapbase-expanded-source-develop\sp\src\game\gamepadui\Debug_mod_ez1\\gamepadui.dll	GamepadUI (EZ2)

**Comment by DasMaddi** [comment]
That error is not the fault of GamepadUI. this repo is only tested with a stock copy of SDK 2013. Please contact the mapbase team for assistance.

**Comment by breakdowngamesYT** [comment]
ok i fixed it i had to declare the some code shit but how do i get it to appear in game
