### ISSUE TITLE
Linker error related to PostMessageToAllSiblingsOfType, with possible solution.

### ISSUE THREAD

**Issue by Bitl** [Joshua-Ashton/HL2-GamepadUI#18]
When I compile this under my mod's codebase, a Linker error gets displayed.

```
Error	LNK2019	unresolved external symbol "public: void __thiscall vgui::Panel::PostMessageToAllSiblingsOfType<class GamepadUIButton>(class KeyValues *,float)" (??$PostMessageToAllSiblingsOfType@VGamepadUIButton@@@Panel@vgui@@QAEXPAVKeyValues@@M@Z) referenced in function "public: virtual void __thiscall GamepadUIButton::FireActionSignal(void)" (?FireActionSignal@GamepadUIButton@@UAEXXZ)	GamepadUI (FR)	G:\Projects\GitHub\FIREFIGHT-RELOADED-src-sdk-2013\sp\src\game\gamepadui\gamepadui_button.obj	1	
```

I found a solution to this by commenting the #if and #endif defines in Panel.h: https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/vgui_controls/Panel.h#L952

However, I have not yet checked if this is stable.

**Comment by DasMaddi** [comment]
This is stable and was merely missed in the readme upon initial commit. Apologies. I will correct this now.

**Comment by Bitl** [comment]
I can confirm this is stable.
![image](https://user-images.githubusercontent.com/5020096/218658269-3c0661df-1314-4189-88a5-dea9720a46cb.png)

**Comment by DasMaddi** [comment]
Fixed and clarified on the readme.
