### ISSUE TITLE
Settings pages jump to bottom when hovering over other tabs with mouse

### ISSUE THREAD

**Issue by Luke18033** [Joshua-Ashton/HL2-GamepadUI#22]
https://user-images.githubusercontent.com/19228201/218704831-4b904edd-fdad-4922-9851-ad574e16084d.mp4

This happens in the SDK 2013 build and the versions included with Portal/HL2

**Comment by SanyaSho** [comment]
> SDK 2013
can confirm it in TF2 engine custom build

**Comment by DasMaddi** [comment]
merged #23 fixes this.
