### ISSUE TITLE
GitHub Actions CI for Gamepad UI

### ISSUE THREAD

**Issue by Blixibon** [Joshua-Ashton/HL2-GamepadUI#25]
GitHub Actions allows the source code to be compiled automatically in response to incoming pull requests and/or commits pushed to the main branch. This helps ensure that the code remains compatible with all platforms and both Source 2013 branches, and allows compiled binaries for the latest commits to remain available at almost all times.

The Gamepad UI repository is isolated from the original Source 2013 code, so it would have to draw it from elsewhere and plug the Gamepad UI into it. [VPhysics Jolt](https://github.com/Joshua-Ashton/VPhysics-Jolt) is similarly isolated, but it [already integrates GitHub Actions](https://github.com/Joshua-Ashton/VPhysics-Jolt/blob/main/.github/workflows/artifacts.yml) by drawing from a ["mini" Source SDK base](https://github.com/Joshua-Ashton/mini-source-sdk) containing the essentials and changes needed to compile it. The same method could potentially be used by Gamepad UI to compile for both Source 2013 SP and MP.

**Comment by DasMaddi** [comment]
@Joshua-Ashton would need to approve and set this one up. I have no experience with CI.
