### ISSUE TITLE
How do you enable this I put -gamepadui on my Lauch options

### ISSUE THREAD

**Issue by breakdowngamesYT** [Joshua-Ashton/HL2-GamepadUI#29]

**Comment by Blixibon** [comment]
Did you add the changes from this repository's `src/game/client/cdll_client_int.cpp` file?

**Comment by DasMaddi** [comment]
Looks like the readme could use a small clarification that GAMEPADUI needs to be defined somewhere in the preprocessor blocks in your client VPC script. I'll make that change.

**Comment by breakdowngamesYT** [comment]
what do i need to do? to the vpc

**Comment by DasMaddi** [comment]
Please check the new readme.
