### ISSUE TITLE
[ Enhancement ] Overriding GameUI.dll from mod folder instead of the SDK folder

### ISSUE THREAD

**Issue by Nbc66** [Joshua-Ashton/HL2-GamepadUI#3]
have a way for the DLL to be loaded from the mod folder
so it's easier for mods to distribute the gameui.dll without people needing to
go into their SDK folder and replace the file manually

**Comment by Nbc66** [comment]
might need to edit the engine code itself to do a check in the mod folder first and if no gameui.dll is found load it from the SDK gameui.dll 

or ideally, the best way would be to push the gameui.dll to the SDK directly to the steam depot

**Comment by DasMaddi** [comment]
This is not possible within the scope of this project.

**Comment by Nbc66** [comment]
That's sad to hear looks like only mods that are on steam will be abel to override gameu.dll

**Comment by FriskTheFallenHuman** [comment]
There's actually ways to override the gameui.dll from a mod scope you need to drop this snipe code in both cdll_client_init/gameinterface.cpp

```
//#pragma message(FILE_LINE_STRING " !!FIXME!! replace all this with Sys_LoadGameModule")
static class DllOverride {
	public:
		DllOverride() {
			Sys_LoadInterface( "filesystem_stdio.dll", FILESYSTEM_INTERFACE_VERSION, nullptr, (void **)&g_pFullFileSystem );
			const char *pGameDir = CommandLine()->ParmValue( "-game", "hl2" );
			pGameDir = VarArgs( "%s/bin", pGameDir );
			g_pFullFileSystem->AddSearchPath( pGameDir, "EXECUTABLE_PATH", PATH_ADD_TO_HEAD );
		}
} g_DllOverride;
```

be aware that the dll may not work for mp due to interface differences. and that there's better ways to hide the menu and logo

**Comment by DasMaddi** [comment]
This method is highly unsafe as the engine still loads the original gameUI dll.

**Comment by FriskTheFallenHuman** [comment]
> This method is highly unsafe as the engine still loads the original gameUI dll.

from my testing i've never encounter issues with it, again there's a better way to do this

**Comment by DasMaddi** [comment]
I think for now, we ought to leave this up to individual modders to implement on an as-needed basis on their projects. Pinging @Joshua-Ashton for his thoughts.

**Comment by DasMaddi** [comment]
Closing for now until a cleaner method can be established. For now this is the best I believe we can do.
