### ISSUE TITLE
how to change the title font for gamepad ui and there are two titles for some reason

### ISSUE THREAD

**Issue by breakdowngamesYT** [Joshua-Ashton/HL2-GamepadUI#31]
![Entropy Zero 16_02_2023 15_21_16](https://user-images.githubusercontent.com/83152033/219510218-498342de-7e62-499c-b995-12e00ed8ef93.png)

**Comment by DasMaddi** [comment]
You need to use our GameUI dll that we provided. Read the readme.

Please see this page for assistance with using GamepadUI. https://developer.valvesoftware.com/wiki/Gamepad_UI_in_mods
