### ISSUE TITLE
Gamepad ui force scales the portal gun overlay.

### ISSUE THREAD

**Issue by Bitwolfies** [Joshua-Ashton/HL2-GamepadUI#41]
Not sure if its *specifically* the fault of the gamepadui, but it sure only engages when its on. 

Normal: 
![Screenshot_20230330_022017](https://user-images.githubusercontent.com/65789901/228790635-4394e7f1-ff3a-48e6-9c4e-879d6257744f.png)

Gamepadui:
![Screenshot_20230330_021727](https://user-images.githubusercontent.com/65789901/228790133-99b37ff1-dcdb-40ad-b63a-f98964a8e518.png)
Clearly this was for the deck, but it doesn't look so good on desktop.

**Comment by Joshua-Ashton** [comment]
This is done in the game code.
