### ISSUE TITLE
UI is still broken after gamepadui implementation

### ISSUE THREAD

**Issue by funniman-exe** [Joshua-Ashton/HL2-GamepadUI#46]
I am using The Portal 2007 Client Source Code ported to 2013.
Even Though gamepadui is setup properly, the random white square in the middle of the HUD, and the HEV Suit Hud being misplaced to the upper left hand corner are still occuring. Even when running with -gamepadui.
Do you have any idea why this is happening? Am I missing Something.
Please Help.

**Comment by DasMaddi** [comment]
GamepadUI does not affect the HUD in any capacity. 

In addition, this was tested for only stock SDK2013 from the official Valve repository. We cannot guarantee compatibility with community versions or custom forks.
