### ISSUE TITLE
'OnRenderStart': is not a member of 'IRopeManager'

### ISSUE THREAD

**Issue by bulkmoerls** [Joshua-Ashton/HL2-GamepadUI#49]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2039	'OnRenderStart': is not a member of 'IRopeManager'	Client (Episodic)	C:\Users\ 
[username]\Documents\XBLAH\content\Mapbase\mymod3\src\game\client\cdll_client_int.cpp	2240		

BASE USED: MAPBASE

**Comment by DasMaddi** [comment]
Mapbase is not the default SDK2013 and is out of scope for the support we are able to provide
