### ISSUE TITLE
Hangs on launch with ui/gamestartup.mp3 files

### ISSUE THREAD

**Issue by Luke18033** [Joshua-Ashton/HL2-GamepadUI#6]
MP3 files in the `ui/` folder starting with `gamestartup` will be randomly, automatically played on the main menu in the desktop UI, but in gamepad UI these files being present will cause the engine to hang on startup.

This breaks mods such as Portal: Prelude which use this for menu music.

**Comment by DasMaddi** [comment]
Fixed in #10
