### ISSUE TITLE
Typo in overriding menu console message

### ISSUE THREAD

**Issue by Luke18033** [Joshua-Ashton/HL2-GamepadUI#7]
Very minor nitpick. When the game starts, the message `[GamepadUI] Overiding menu.` is printed to the console. "Overiding" is incorrect, it should be "overriding" with two Rs.

**Comment by Nbc66** [comment]
you can make a pull request

**Comment by Luke18033** [comment]
Good point, you don't really need to properly know C++ to edit 1 character in a string...
