### ISSUE TITLE
Weird artifacts appear in logo and some other places

### ISSUE THREAD

**Issue by notfoundname** [Joshua-Ashton/HL2-GamepadUI#8]
![image](https://user-images.githubusercontent.com/48317169/218340108-76dae010-3dc0-4a7d-8bef-2efbfb21a1aa.png)
![image](https://user-images.githubusercontent.com/48317169/218340115-9ce25818-4bff-4d77-8175-d277357dc728.png)
Any way to get rid of them?

**Comment by ledmic** [comment]
its encoding errors, its fixed in [this](https://github.com/Nbc66/source-sdk-2013-ce/commit/11d0a99a8dc879e7b3c38904d3161e987f9c1b5d) commit

**Comment by DasMaddi** [comment]
Closing as done in #13
